version: '3.8'
services:
  app:
    container_name: fashion_blog_app
    image: 'fashion-blog-api:latest'
    build:
      context: .
    ports:
      - "8085:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://fashion_blog_db:5432/fashion_blog
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - fashion_blog_db


  fashion_blog_db:
    container_name: fashion_blog_db
    image: 'postgres:latest'
    ports:
      - '5433:5432'
    environment:
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - POSTGRES_DB=fashion_blog
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./log-directory:/var/lib/postgresql/data
    networks:
      - postgres


  pgadmin:
    container_name: pgadmin_view
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: richie@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "8089:80"
    networks:
      - postgres
    restart: unless-stopped


networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:




